### ISSUE TITLE
Fact | En una misma reserva no se puede reservar habitaciones de hoteles distintos

### ISSUE THREAD

**Issue by Juan2k-1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#11]

**Comment by CarlosCano01** [comment]
fact "Habitaciones reservadas en el mismo hotel"{
	all  r1 : Reserva|   r1.habitacionesReservadas in r1.hotel.habitaciones
}

**Comment by SaulRC1** [comment]
fact "Habitaciones reservadas en el mismo hotel"{
	all r: Reserva | let h = r.hotel | r.habitacionesReservadas in h.habitaciones
}
