### ISSUE TITLE
Fact | El conjunto de habitaciones reservadas no puede ser superior al conjunto de habitaciones del hotel

### ISSUE THREAD

**Issue by Juan2k-1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#12]

**Comment by chiwii8** [comment]
fact "El conjunto de habitaciones reservadas no puede ser superior al conjunto de habitaciones del hotel"{
	---El conjunto de habitaciones reservadas no puede ser superior al conjunto de habitaciones del hotel
	---Todas las habitaciones reservadas son de un mismo hotel
	---El conjunto de habitaciones tienen que estar contenidas en el hotel
	all r: Reserva | one h: Hotel | #r.habitacionesReservadas <= #h.habitaciones   and r.habitacionesReservadas in h.habitaciones
					and r.hotel = h
}

**Comment by SaulRC1** [comment]
fact "El conjunto de habitaciones reservadas no puede ser superior al conjunto de habitaciones del hotel"{
	all r: Reserva | #r.habitacionesReservadas <= #r.hotel.habitaciones
}
