### ISSUE TITLE
Funciones de Fact "Reserva correcta de habitación"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#15]
Sacar las funciones que se puedan del Fact siguiente:

![Image](https://user-images.githubusercontent.com/91340866/236012639-9aa56faf-5a8f-4cb9-9c55-b302f9b9fc26.png)

**Comment by chiwii8** [comment]
fun Fecha_Iguales[f1,f2:Fecha]:Bool{
	f1 = f2 implies True else False
}

**Comment by SaulRC1** [comment]
-- Devuelve las habitaciones en comun de dos reservas distintas
fun habitacionesEnComun[r1: Reserva, r2: Reserva] : set Habitacion {
    r1.habitacionesReservadas & r2.habitacionesReservadas
}

-- Comprueba si dos reservas comparten habitaciones reservadas
fun compartenHabitaciones[r1: Reserva, r2:Reserva] : Bool {
    #habitacionesEnComun[r1, r2] > 0 implies True else False
}
