### ISSUE TITLE
Funciones de Fact "Distintas habitaciones"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#16]
Sacar las funciones que se puedan del siguiente Fact:

![Image](https://user-images.githubusercontent.com/91340866/236013128-1f0383ce-8f33-4aa5-b955-077e4dca0d95.png)

**Comment by chiwii8** [comment]
fun Numero_Reservas[]: Int{
	#Reserva
}

fun numero_hab_Reservada[h:Habitacion,r:Reserva]: Bool {
	h in r.habitacionesReservadas implies True else False
}
