### ISSUE TITLE
Predicados de Fact "Dni es correcto" y "Dni único"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#19]

**Comment by Juan2k-1** [comment]
pred DniCorrecto {
	 all dni: Dni | #dni.parteNumeros = 8 and #dni.parteLetra = 1
}
pred DniUnico {
    all disj p1, p2 : Persona | not p1.dni = p2.dni

    --Toda persona debe tener un Dni     
    all d: Dni | one p: Persona | d in p.dni
}

**Comment by SaulRC1** [comment]
Dejar comentarios y hacer el run necesario
