### ISSUE TITLE
Fact | El DNI debe de ser único y tener 9 valores como máximo

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#2]

**Comment by Juan2k-1** [comment]
module Complejo_Hotelero

open util/sequniv
open util/integer

sig Dni {
     parteLetra: some Letras, 
     parteNumeros: some Numeros 
}

enum Letras {T, R, W, A, G, M, Y, F, P, D, X, B, N, J, Z, S, Q, V, H, L, C, K, E}
enum Numeros {cero, uno, dos, tres, cuatro, cinco, seis, siete, ocho, nueve}


fact "Dni único" {
	 all disj p1, p2 : Persona | not p1.dni =  p2.dni
}

fact "Dni es correcto" {
   all dni: Dni |
        #dni.parteNumeros = 8 and
        #dni.parteLetra = 1  
	
}
