### ISSUE TITLE
Predicados de Fact "Todas las personas deben estar asociadas a un hotel"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#22]

**Comment by Juan2k-1** [comment]
pred TodosLasPersonasAsociadasAUnHotel {

	-- Todas las personas deben estar relacionadas con un hotel
	all p: Persona | one h: Hotel | p in h.personas

	-- Dos hoteles distintos no pueden tener a las mismas personas
	-- registradas
	all disj h1, h2 : Hotel | disj[h1.personas, h2.personas]
}

**Comment by SaulRC1** [comment]
Dejar comentarios y el comando run necesario
