### ISSUE TITLE
Predicados de Fact "Distintas Habitaciones"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#23]

**Comment by chiwii8** [comment]
pred DistintasHabitaciones {

    -- Dos habitaciones no pueden estar en un mismo hotel
    all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones

    -- One habitación siempre debe estar en un hotel
    all hab1:Habitacion | one h1 : Hotel | hab1 in h1.habitaciones

    -- Número máximo de llaves electrónicas por habitación es 2
	all h : Habitacion | #h.llavesElectronicas <= 2

    -- Cuando una habitación está reservada, esta debe tener 2 llaves electronicas
	all h: Habitacion, r: Reserva |numero_hab_Reservada[h,r] = True implies #h.llavesElectronicas = 2 else #h.llavesElectronicas = 1

	-- Cuando una habitación no está reservada porqué no existe una reserva, debe tener como máximo 1 llave
	all h: Habitacion | Numero_Reservas[] = 0 implies #h.llavesElectronicas = 1
}

**Comment by chiwii8** [comment]
-- Hay que comentar fact Distintas habitaciones para poder utilizar este run

-- Una vez realizada la primera restriccion en el fact "Reserva correcta de habitacion"
-- se comprueba que dos hoteles compartan habitaciones , estas 
-- 
-- De este predicado se deduce la primera restricción en el fact "Distintas habitaciones"
pred HabitacionesMasHoteles {
    -- Dos habitaciones pueden estar en un mismo hotel
    all disj h1, h2 :Hotel | some hab:Habitacion | hab in h1.habitaciones and hab in h2.habitaciones
    --all disj h1, h2 :Hotel |  h1.habitaciones=h2.habitaciones
}
--run HabitacionesMasHoteles  for 20 but 20 seq,6 int, exactly  2 Hotel , exactly 5 Habitacion

-- Una vez realizada la primera restriccion en el fact "Distintas habitaciones"
-- se comprueba que las habitaciones estan asociadas a un hotel 
--
-- De este predicado se complementa la primera restricción en el fact "Distintas habitaciones"
pred HabitacionIndependienteHotel{
	---Puede haber habitaciones que no esten en ningún hotel
	all h: Hotel | some hab:Habitacion | not hab in h.habitaciones or hab in h.habitaciones
}

--run HabitacionIndependienteHotel  for 20 but 20 seq,6 int, exactly  2 Hotel , exactly 5 Habitacion



-- Una vez realizada las restricciones en el fact "Distintas habitaciones"
-- se comprueba que las habitaciones cumplan la regla de negocio con valores Erróneos
-- según el modelo planteado 

-- De este predicado se complementa las siguientes restricciónes en el fact "Distintas habitaciones"
-- Para que se cumpla con la regla de negocio establecida en la practica 1 
pred LlavesHabitacionesMaximo {
	all h : Habitacion | #h.llavesElectronicas <= 5
	all h: Habitacion, r: Reserva | estaReservada[h,r] = True implies #h.llavesElectronicas = 5 else #h.llavesElectronicas = 3
	all h: Habitacion | numeroDeReservas[] = 0 implies #h.llavesElectronicas = 2
}

--run LlavesHabitacionesMaximo  for 20 but 20 seq,6 int,exactly 2 Hotel,exactly 3 Habitacion,exactly 1 Reserva
--run LlavesHabitacionesMaximo  for 20 but 20 seq,6 int,exactly 2 Hotel,exactly 3 Habitacion,exactly 0 Reserva
