### ISSUE TITLE
Asertos de Fact "Distintas Habitaciones"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#27]

**Comment by chiwii8** [comment]
---inicio de los asertos del fact "Distintas habitaciones"----

--Los asertos se han dividido en la primera parte del código que es válida y los contraEjemplos

--Este aserto tiene lugar en la primera restriccion del fact "Distintas habitaciones"
--En este primer aserto verificamos que una habitacion no puede estar en dos hoteles distintos,
--Como contraejemplo se ha empleado el pred HabitacionesMasHoteles
assert UnaHabitacionNoPuedeEstarEnVariosHoteles{
	all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones
	--HabitacionesMasHoteles
}
--check UnaHabitacionNoPuedeEstarEnVariosHoteles  for 10 but 20 seq, 6 Int

--Este aserto tiene lugar en la primera restriccion del fact "Distintas habitaciones"
--En este primer aserto verificamos que una habitacion no puede estar en dos hoteles distintos,
--Aqui no se ha aplicado el predicado  HabitacionesMasHoteles como contraejemplo ya que como indica una posibilidad de que una habitacion
--no este asociada a un hotel, siempre toma la acción de asociar la habitacion a un hotel
--Todas las habitaciones no estan asociadas a ningún hotel
assert UnaHabitacionEstaEnUnUnicoHotel{
	--Una habitacion debe estar asociada a un hotel, correcto
	all hab1:Habitacion | one h1 : Hotel | hab1 in h1.habitaciones

	--all hab1:Habitacion | one h1 : Hotel | not hab1 in h1.habitaciones
}
---check UnaHabitacionEstaEnUnUnicoHotel for 20 but 20 seq,6 int, exactly  1 Hotel , exactly 5 Habitacion

---Este aserto comprueba que se cumplan las condiciones referentes al número de llaves electrónicas
---Valido, comprueba los valores empleados en el fact
---Como contraejemplo se emplea el predicado LlavesHabitacionesMaximo que tiene otras limitaciones de la regla de negocio
assert LlavesPorHabitacionSeCumple{
	all h : Habitacion | #h.llavesElectronicas <= 2
	all h: Habitacion, r: Reserva | estaReservada[h,r] = True implies #h.llavesElectronicas = 2 else #h.llavesElectronicas = 1
	all h: Habitacion | numeroDeReservas[] = 0 implies #h.llavesElectronicas = 1
	--LlavesHabitacionesMaximo
	
}
---check LlavesPorHabitacionSeCumple for 20 but 20 seq,6 int,exactly 1 Habitacion , 1 Reserva, exactly 1 Hotel

--- Fin asertos del fact "Distintas habitaciones" ---
