### ISSUE TITLE
Asertos de Fact "Tarjetas unicas de clientes"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#28]

**Comment by chiwii8** [comment]
--- Inicio de los asertos del fact "Tarjetas unicas de clientes"

--En este aserto comprobamos que las tarjetas sean propias de cada cliente
--Para ello se ha tomado como validación los datos del fact "Tarjetas unicas de clientes"
--Como contraejemplo se ha supuesto que existan tarjetas sin clientes
assert TarjetasUnicasDeClientes{
	all t:TarjetaDePago | one c: Cliente | t in c.tarjetaDePago
	--all t:TarjetaDePago | no c:Cliente| t in c.tarjetaDePago
}

check TarjetasUnicasDeClientes for 10 but 20 seq,6 int

---Fin  de los asertos del fact "Tarjetas unicas de clientes"
