### ISSUE TITLE
Asertos de Fact "LlaveElectronica una habitacion"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#29]

**Comment by Juan2k-1** [comment]
assert UnaHabitacionUnaLlaveElectronica {
	 all disj hab1,hab2:Habitacion, Ll: LlaveElectronica | Ll in hab1.llavesElectronicas implies not Ll in hab2.llavesElectronicas
	--all disj hab1, hab2:Habitacion, Ll: LlaveElectronica | Ll in hab1.llavesElectronicas implies Ll in hab2.llavesElectronicas
}
check UnaHabitacionUnaLlaveElectronica for 10 but 20 seq, 6 Int, exactly 2 Habitacion, exactly 3 LlaveElectronica
