### ISSUE TITLE
Fact | Número de habitacion coincide con el identificador de llave

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#3]

**Comment by Juan2k-1** [comment]
module Complejo_Hotelero2

open util/sequniv
open util/integer

enum TipoHabitacion {Suite, Simple, Doble}

--Creamos un signatura Identificador para almacenar el id tanto de las llaves como de las habitaciones
sig Identificador {
	id: Int
}

sig Habitacion {
    llavesElectronicas : some LlaveElectronica,
    categoria : one Categoria,
    tipoHabitacion : one TipoHabitacion,
	numHabitacion : one Identificador
}

sig LlaveElectronica {
	idLlave: Identificador
}

sig Categoria {}

fact "Numero de habitacion coincide con el identificador de llave" {
	all hab: Habitacion | hab.llavesElectronicas.idLlave.id = hab.numHabitacion.id
	
	--Restricción adicional para que todos los identificadores sean mayores que cero
	all i: Identificador | i.id > 0    
}

--Este Fact ya estaba en el modelo anteriormente
fact "LlaveElectronica una habitacion"{
    all disj hab1,hab2:Habitacion, Ll: LlaveElectronica | Ll in hab1.llavesElectronicas implies not Ll in hab2.llavesElectronicas
}

--Restricción adicional para que los identificadores de las habitaciones sean únicos
fact "Identificadores únicos de las habitaciones" {
	all disj h1, h2: Habitacion | h1 != h2 implies h1.numHabitacion.id != h2.numHabitacion.id
}

--Restricción adicional para que los identificadores de las llaves sean únicos
fact "Identificadores únicos de las llaves" {
	all l1, l2: LlaveElectronica | l1 != l2 => l1.idLlave.id != l2.idLlave.id
}
