### ISSUE TITLE
Asertos de Fact "un gerente por hotel"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#30]

**Comment by CarlosCano01** [comment]
assert un_gerente_por_hotel{
		all em: Empleado | em.tipoEmpleado !=Gerente 
}
check un_gerente_por_hotel for 4 but 20 seq,6 int ,exactly 1 Hotel,  exactly 1 Empleado, exactly 1 Proveedor

esto da un contraejemplo

assert un_gerente_por_hotel{
		 all h :Hotel | one em: Empleado | em.tipoEmpleado = Gerente and em in h.personas
}
check un_gerente_por_hotel for 4 but 20 seq,6 int ,exactly 1 Hotel,  exactly 1 Empleado, exactly 1 Proveedor

esto no da un contraejemplo

**Comment by CarlosCano01** [comment]
assert no_existe_gerente_por_hotel{
all em: Empleado | em.tipoEmpleado !=Gerente
}
check un_gerente_por_hotel for 4 but 20 seq,6 int ,exactly 1 Hotel, exactly 1 Empleado, exactly 1 Proveedor

--esto da un contraejemplo

assert un_gerente_por_hotel{
all h :Hotel | one em: Empleado | em.tipoEmpleado = Gerente and em in h.personas
}
check un_gerente_por_hotel for 4 but 20 seq,6 int ,exactly 1 Hotel, exactly 1 Empleado, exactly 1 Proveedor

--esto no da un contraejemplo
