### ISSUE TITLE
Asertos de Fact "una habitación por categoría"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#32]

**Comment by chiwii8** [comment]
---Inicio de los asertos del fact "una habitacion por categoria"

---En este aserto estamos comprobando que una habitacion tiene una única categoria
---Para ello para la validación se ha cogido la restriccion del fact "una habitacion por categoria" 

--Como contraejemplos se han seleccionado dos
-- 1. categoria no tiene habitaciones
-- 2.Que una categoría únicamente tenga una habitación 
assert UnaHabitacionTieneUnaUnicaCategoria{
	all c: Categoria | some hab: Habitacion | c = hab.categoria
	--Contraejemplos	
	--all c: Categoria | one hab: Habitacion | c = hab.categoria
	--all c: Categoria, hab: Habitacion | c != hab.categoria	
}
--check UnaHabitacionTieneUnaUnicaCategoria  for 10 but 20 seq,6 int 

---Fin de los asertos del fact "una habitacion por categoria"
