### ISSUE TITLE
Asertos de Fact "Numero de habitacion coincide con el identificador de llave"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#34]

**Comment by Juan2k-1** [comment]
assert NumeroHabitacionCoincideConLlave {
	 all hab: Habitacion | hab.llavesElectronicas.idLlave = hab.numHabitacion
	 --all hab: Habitacion | hab.llavesElectronicas.idLlave != hab.numHabitacion
}
check NumeroHabitacionCoincideConLlave for 10 but 20 seq, 6 Int, exactly 2 Habitacion, exactly 1 Hotel, exactly 4 LlaveElectronica
