### ISSUE TITLE
Asertos de Fact "Cliente que haya hecho una reserva debe estar registrado en el hotel"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#35]

**Comment by CarlosCano01** [comment]
assert distintoshotels{
	all disj h1,h2 :Hotel , c:Persona | c in h1.personas and not(c in h2.personas)
}
check distintoshotels for 4 but 20 seq,6 int ,exactly 2 Hotel,  exactly 5 Cliente, exactly 1 Proveedor

esto no da contraejemplo
