### ISSUE TITLE
Asertos de Fact "Identificadores únicos de las habitaciones"

### ISSUE THREAD

**Issue by SaulRC1** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#36]

**Comment by Juan2k-1** [comment]
assert IdentificadoresUnicosDeLasHabitaciones {
	 all disj h1, h2: Habitacion | h1 != h2 implies h1.numHabitacion != h2.numHabitacion
	 --all disj h1, h2: Habitacion | h1 != h2 implies h1.numHabitacion != h2.numHabitacion
}
check IdentificadoresUnicosDeLasHabitaciones for 10 but 20 seq, 6 Int, exactly 2 Habitacion
