### ISSUE TITLE
Fact | Una habitación solo puede estar en un mismo hotel y como máximo tener dos llaves electrónicas

### ISSUE THREAD

**Issue by CarlosCano01** [SaulRC1/Metodos-Formales-en-Ingenier-a-del-Software#4]

**Comment by CarlosCano01** [comment]
fact "Distintas habitaciones"{
     all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones

    all hab1:Habitacion , h1 : Hotel | hab1 in h1.habitaciones

    all hab1:Habitacion , r1 : Reserva|  not hab1 in r1.habitacionesReservadas implies #hab1.llavesElectronicas = 1

    all hab1:Habitacion , r1 : Reserva|   hab1 in r1.habitacionesReservadas implies #hab1.llavesElectronicas = 2

    all disj hab1, hab2 :Habitacion | not hab1.llavesElectronicas=hab2.llavesElectronicas
}

**Comment by CarlosCano01** [comment]
fact "Distintas habitaciones"{
all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones

all hab1:Habitacion | one h1 : Hotel | hab1 in h1.habitaciones

all hab1:Habitacion , r1 : Reserva|  not hab1 in r1.habitacionesReservadas implies #hab1.llavesElectronicas = 1

all hab1:Habitacion , r1 : Reserva|   hab1 in r1.habitacionesReservadas implies #hab1.llavesElectronicas = 2

all disj hab1, hab2 :Habitacion | not hab1.llavesElectronicas=hab2.llavesElectronicas
}

**Comment by SaulRC1** [comment]
Se han encontrado fallos. Hay que cambiar la comprobación para hacer que como máximo una habitación tenga dos llaves electrónicas, y que cuando se reserve, tenga esas dos.

Lo único válido es:

fact "Distintas habitaciones" {
    all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones

    all hab1:Habitacion | one h1 : Hotel | hab1 in h1.habitaciones
}

**Comment by SaulRC1** [comment]
fact "Distintas habitaciones" {

    -- Dos habitaciones no pueden estar en un mismo hotel
    all disj h1, h2 :Hotel | not h1.habitaciones=h2.habitaciones

    -- One habitación siempre debe estar en un hotel
    all hab1:Habitacion | one h1 : Hotel | hab1 in h1.habitaciones

    -- Número máximo de llaves electrónicas por habitación es 2
	all h : Habitacion | #h.llavesElectronicas <= 2

    -- Cuando una habitación está reservada, esta debe tener 2 llaves electronicas
	all h: Habitacion, r: Reserva | h in r.habitacionesReservadas implies #h.llavesElectronicas = 2
}
